"""
csv_to_sql.py
─────────────
Utility to import the production CSV into a fresh SQL database.
Use this if you need to re-seed from the CSV, or to import
into a different SQL engine (PostgreSQL, MySQL, etc.).

Usage:
  python csv_to_sql.py                        # import CSV → SQLite (default)
  python csv_to_sql.py --engine postgres       # import CSV → PostgreSQL
  python csv_to_sql.py --check                # just validate the CSV
"""

import csv
import sqlite3
import os
import sys
import argparse
from datetime import datetime

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CSV_PATH = os.path.join(BASE_DIR, "data", "production_output.csv")
DB_PATH  = os.path.join(BASE_DIR, "data", "production.db")

EXPECTED_HEADERS = [
    "order_id","tanggal","shift","divisi","produk","no_mesin","operator",
    "jumlah_roll","berat_kg","panjang_m","lebar_cm","tebal_micron",
    "warna","keterangan","created_at"
]

def load_csv(path: str) -> list[dict]:
    with open(path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        # Validate headers
        missing = [h for h in EXPECTED_HEADERS if h not in (reader.fieldnames or [])]
        if missing:
            raise ValueError(f"CSV missing columns: {missing}")
        return list(reader)

def validate_rows(rows: list[dict]) -> tuple[list, list]:
    valid, errors = [], []
    for i, r in enumerate(rows, 2):  # row 2 = first data row
        errs = []
        if not r.get("order_id"):          errs.append("Missing order_id")
        if not r.get("tanggal"):           errs.append("Missing tanggal")
        try: int(r.get("jumlah_roll", ""))
        except: errs.append("Invalid jumlah_roll")
        try: float(r.get("berat_kg", ""))
        except: errs.append("Invalid berat_kg")
        if errs:
            errors.append({"row": i, "order_id": r.get("order_id", "?"), "errors": errs})
        else:
            valid.append(r)
    return valid, errors

def import_to_sqlite(rows: list[dict], db_path: str):
    conn = sqlite3.connect(db_path)
    c = conn.cursor()
    c.execute("""
        CREATE TABLE IF NOT EXISTS production_output (
            id             INTEGER PRIMARY KEY AUTOINCREMENT,
            order_id       TEXT    NOT NULL UNIQUE,
            tanggal        TEXT    NOT NULL,
            shift          TEXT    NOT NULL,
            divisi         TEXT    NOT NULL,
            produk         TEXT    NOT NULL,
            no_mesin       TEXT    NOT NULL,
            operator       TEXT    NOT NULL,
            jumlah_roll    INTEGER NOT NULL,
            berat_kg       REAL    NOT NULL,
            panjang_m      REAL,
            lebar_cm       REAL,
            tebal_micron   REAL,
            warna          TEXT,
            keterangan     TEXT,
            created_at     TEXT    NOT NULL
        )
    """)
    inserted, skipped = 0, 0
    for r in rows:
        try:
            c.execute("""
                INSERT OR IGNORE INTO production_output
                    (order_id,tanggal,shift,divisi,produk,no_mesin,operator,
                     jumlah_roll,berat_kg,panjang_m,lebar_cm,tebal_micron,
                     warna,keterangan,created_at)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
            """, (
                r["order_id"], r["tanggal"], r["shift"], r["divisi"],
                r["produk"], r["no_mesin"], r["operator"],
                int(r["jumlah_roll"]), float(r["berat_kg"]),
                float(r["panjang_m"])    if r.get("panjang_m")    else None,
                float(r["lebar_cm"])     if r.get("lebar_cm")     else None,
                float(r["tebal_micron"]) if r.get("tebal_micron") else None,
                r.get("warna",""), r.get("keterangan",""),
                r.get("created_at", datetime.now().isoformat()),
            ))
            if c.rowcount: inserted += 1
            else:          skipped  += 1
        except Exception as e:
            print(f"  ⚠  Skipping {r.get('order_id')}: {e}")
            skipped += 1
    conn.commit()
    conn.close()
    return inserted, skipped

def print_sql_for_postgres(rows: list[dict]):
    """Print INSERT statements for PostgreSQL / MySQL / any SQL engine."""
    print("-- Generated by csv_to_sql.py")
    print("-- Paste into your SQL client\n")
    print("""CREATE TABLE IF NOT EXISTS production_output (
    id             SERIAL PRIMARY KEY,
    order_id       VARCHAR(50)  NOT NULL UNIQUE,
    tanggal        DATE         NOT NULL,
    shift          VARCHAR(40)  NOT NULL,
    divisi         VARCHAR(50)  NOT NULL,
    produk         VARCHAR(100) NOT NULL,
    no_mesin       VARCHAR(20)  NOT NULL,
    operator       VARCHAR(80)  NOT NULL,
    jumlah_roll    INTEGER      NOT NULL,
    berat_kg       NUMERIC(10,2) NOT NULL,
    panjang_m      NUMERIC(10,2),
    lebar_cm       NUMERIC(10,2),
    tebal_micron   NUMERIC(10,3),
    warna          VARCHAR(50),
    keterangan     TEXT,
    created_at     TIMESTAMP    NOT NULL
);\n""")
    for r in rows:
        vals = [
            f"'{r['order_id']}'", f"'{r['tanggal']}'", f"'{r['shift']}'",
            f"'{r['divisi']}'",   f"'{r['produk']}'",  f"'{r['no_mesin']}'",
            f"'{r['operator']}'",
            str(int(r["jumlah_roll"])), str(float(r["berat_kg"])),
            str(float(r["panjang_m"]))    if r.get("panjang_m")    else "NULL",
            str(float(r["lebar_cm"]))     if r.get("lebar_cm")     else "NULL",
            str(float(r["tebal_micron"])) if r.get("tebal_micron") else "NULL",
            f"'{r.get('warna','')}'",
            f"'{r.get('keterangan','').replace(chr(39), chr(39)*2)}'",
            f"'{r.get('created_at', datetime.now().isoformat())}'",
        ]
        print(f"INSERT INTO production_output (order_id,tanggal,shift,divisi,produk,no_mesin,operator,jumlah_roll,berat_kg,panjang_m,lebar_cm,tebal_micron,warna,keterangan,created_at) VALUES ({','.join(vals)}) ON CONFLICT (order_id) DO NOTHING;")

def main():
    parser = argparse.ArgumentParser(description="Import production CSV to SQL")
    parser.add_argument("--csv",    default=CSV_PATH,   help="Path to CSV file")
    parser.add_argument("--db",     default=DB_PATH,    help="Path to SQLite DB (for sqlite engine)")
    parser.add_argument("--engine", default="sqlite",   choices=["sqlite","postgres"], help="Target DB engine")
    parser.add_argument("--check",  action="store_true", help="Only validate CSV, don't import")
    args = parser.parse_args()

    print(f"\n{'='*50}")
    print(f"  CSV → SQL Import Utility")
    print(f"{'='*50}")
    print(f"  CSV:    {args.csv}")
    print(f"  Engine: {args.engine}")
    print()

    if not os.path.exists(args.csv):
        print(f"  ✗ CSV not found: {args.csv}")
        sys.exit(1)

    print("  Loading CSV...")
    try:
        rows = load_csv(args.csv)
    except Exception as e:
        print(f"  ✗ Error: {e}")
        sys.exit(1)
    print(f"  ✓ {len(rows)} rows loaded")

    print("  Validating rows...")
    valid, errors = validate_rows(rows)
    if errors:
        print(f"  ⚠  {len(errors)} rows with errors:")
        for e in errors[:10]:
            print(f"     Row {e['row']} ({e['order_id']}): {', '.join(e['errors'])}")
        if len(errors) > 10:
            print(f"     ... and {len(errors)-10} more")
    print(f"  ✓ {len(valid)} valid rows")

    if args.check:
        print("\n  Check complete (--check mode, no import performed)")
        return

    if args.engine == "sqlite":
        print(f"\n  Importing to SQLite: {args.db}")
        inserted, skipped = import_to_sqlite(valid, args.db)
        print(f"  ✓ Inserted: {inserted}  |  Skipped (duplicates): {skipped}")
    elif args.engine == "postgres":
        print("\n  Generating PostgreSQL INSERT statements...\n")
        print_sql_for_postgres(valid)

    print(f"\n{'='*50}\n  Done.\n{'='*50}\n")

if __name__ == "__main__":
    main()
